apiVersion: v1
kind: Service
metadata:
  name: actor
  labels:
    app: actor
spec:
  ports:
  - name: dapr
    port: 3500
    protocol: TCP
    targetPort: 3500
    nodePort: 30001
  selector:
    app: actor
  type: NodePort
status:
  loadBalancer: {}
